# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c6c8ee7f9cba6cd0a9ed74f9407f0b4641849bef76a65c993aa7ac9a48b6997964af4af51403fc6abb8a544b3de2a8b5522170ffa5b03b856b6da5635d0c8ce

test:
  secret_key_base: 4aa51b9c8e52843ab59a6ecfbba6663e87a1b7274c0f7c848b7d972bd8baca1e5576c0fc1663ffd3524149df64cbc94b7b49ea51baf7d25877dcc29ccee4eaaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
